# -*- coding: utf-8 -*-
"""Webscraping _Mobile_Prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_0d6i7XtZkr4qEqoqqQmUy2RtuiuDcul
"""

import requests
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen as uReq

searchString='iphone'

flipkart_url = "https://www.flipkart.com/search?q=" + searchString
print(flipkart_url)
uClient = uReq(flipkart_url)
flipkartPage = uClient.read()
uClient.close()

flipkart_html = bs(flipkartPage, "html.parser")
bigboxes = flipkart_html.find_all("div", {"class": "bhgxx2 col-12-12"})
del bigboxes[0:2]

len(bigboxes)

productLink = "https://www.flipkart.com" + bigboxes[0].div.div.a['href']
productLink

prodRes = requests.get(productLink)
prod_html = bs(prodRes.text, "html.parser")

cost = prod_html.find_all('div', {'class': "_1vC4OE _3qQ9m1"})

cost[0].text

names=prod_html.find_all('span',{"class":"_35KyD6"})

names[0].text

def price(i):
    productLink = "https://www.flipkart.com" + bigboxes[i].div.div.a['href']
    prodRes = requests.get(productLink)
    prod_html = bs(prodRes.text, "html.parser")
    prices = prod_html.find_all('div', {'class': "_1vC4OE _3qQ9m1"})
    #names=prod_html.find_all('span',{"class":"_35KyD6"})
    return prices[0].text

price(1)

Flipkart_prices=[]
for i in range(10):
    prices=price(i)
    Flipkart_prices.append(prices)

def product_name(i):
    productLink = "https://www.flipkart.com" + bigboxes[i].div.div.a['href']
    prodRes = requests.get(productLink)
    prod_html = bs(prodRes.text, "html.parser")
    names=prod_html.find_all('span',{"class":"_35KyD6"})
    return names[0].text

Mobile_name=[]
for i in range(10):
    names=product_name(i)
    Mobile_name.append(names)

import pandas as pd

df = pd.DataFrame(list(zip(Mobile_name, Flipkart_prices)), 
               columns =['Mobile_name', 'Flipkart_price']) 
df

df.drop(index=3,inplace=True)
df

